"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { FilePlus2, FileText, Loader2, Plus, Search } from "lucide-react";
type Document={id:string;title:string;status:string;project_id:string|null;updated_at:string};
export default function DocumentsPage(){const[documents,setDocuments]=useState<Document[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[creating,setCreating]=useState(false),[title,setTitle]=useState("");
 const load=useCallback(async()=>{setLoading(true);const r=await fetch('/api/documents');const d=await r.json();setDocuments(d.documents??[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);
 async function create(){if(!title.trim())return;setCreating(true);const r=await fetch('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.trim(),content:'',status:'draft'})});const d=await r.json();setCreating(false);if(d.document?.id)window.location.href=`/app/documents/${d.document.id}`}
 const visible=documents.filter(d=>d.title.toLowerCase().includes(query.toLowerCase()));
 return <div className="flex-1 overflow-auto bg-canvas"><div className="mx-auto max-w-[960px] p-4 md:p-8"><header className="mb-6 flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-accent">Durable knowledge</p><h1 className="mt-1 text-2xl font-semibold text-ink">Documents</h1><p className="mt-1 text-sm text-muted">Working notes and reusable records outside chat history.</p></div><button onClick={()=>setCreating(v=>!v)} className="flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-xs font-semibold text-white"><Plus size={14}/>New document</button></header>
 {creating&&<section className="mb-5 flex gap-2 rounded-2xl border border-line bg-surface p-3 shadow-panel"><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==='Enter'&&create()} autoFocus placeholder="Document title" className="min-w-0 flex-1 bg-transparent px-2 text-sm text-ink outline-none placeholder:text-faint"/><button onClick={create} className="rounded-xl bg-accent px-4 py-2 text-xs font-semibold text-white">Create</button></section>}
 <div className="relative mb-5"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search documents" className="w-full rounded-xl border border-line bg-surface py-2.5 pl-9 pr-3 text-sm text-ink outline-none focus:border-accent"/></div>
 {loading?<div className="flex gap-2 p-8 text-muted"><Loader2 className="animate-spin" size={16}/>Loading documents…</div>:visible.length===0?<div className="rounded-2xl border border-dashed border-line p-12 text-center"><FilePlus2 className="mx-auto text-faint"/><p className="mt-3 font-medium text-ink">No documents yet</p><p className="mt-1 text-sm text-muted">Create a durable note or save one from Research.</p></div>:<div className="grid gap-3 md:grid-cols-2">{visible.map(d=><Link key={d.id} href={`/app/documents/${d.id}`} className="group rounded-2xl border border-line bg-surface p-5 hover:border-accent/40 hover:shadow-panel transition-all"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-accent-soft text-accent"><FileText size={16}/></div><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold text-ink">{d.title}</h2><div className="mt-2 flex items-center justify-between"><span className="rounded-full bg-surface-subtle px-2 py-0.5 text-[10px] font-semibold uppercase text-muted">{d.status}</span><span className="text-[10px] text-faint">{new Date(d.updated_at).toLocaleDateString()}</span></div></div></div></Link>)}</div>}</div></div>}
