"use client";
import { useCallback, useEffect, useState } from "react";
import { Brain, Check, Clock, Loader2, Pencil, Trash2, X } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
type Memory={id:string;memory_type:string;content:string;created_at:string;severity:number|null};
export default function MemoryPage(){const[items,setItems]=useState<Memory[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<string|null>(null),[correction,setCorrection]=useState("");
 const load=useCallback(async()=>{setLoading(true);const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("ai_memory_items").select("id,memory_type,content,created_at,severity").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100);setItems(data??[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);
 async function feedback(memory:Memory,type:"confirm"|"correct"|"forget"|"expire",text?:string){const{data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from("memory_feedback").insert({user_id:user.id,memory_id:memory.id,feedback_type:type,correction:text||null});if(type==="forget"||type==="expire")setItems(v=>v.filter(x=>x.id!==memory.id));setEditing(null);setCorrection("")}
 return <div className="flex-1 overflow-auto bg-canvas"><div className="mx-auto max-w-[900px] p-4 md:p-8"><header className="mb-6"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-accent">User-controlled context</p><h1 className="mt-1 text-2xl font-semibold text-ink">Memory</h1><p className="mt-1 text-sm text-muted">Confirm, correct, expire, or forget what Buddies believes.</p></header>
 {loading?<div className="flex gap-2 p-8 text-muted"><Loader2 className="animate-spin" size={16}/>Loading memory…</div>:items.length===0?<div className="rounded-2xl border border-dashed border-line p-12 text-center"><Brain className="mx-auto text-faint"/><p className="mt-3 font-medium text-ink">No stored memory</p></div>:<div className="space-y-2">{items.map(m=><article key={m.id} className="rounded-2xl border border-line bg-surface p-4"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-accent-soft text-accent"><Brain size={16}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-surface-subtle px-2 py-0.5 text-[10px] font-semibold uppercase text-muted">{m.memory_type.replaceAll("_"," ")}</span><span className="text-[10px] text-faint">{new Date(m.created_at).toLocaleDateString()}</span></div><p className="mt-2 text-sm leading-relaxed text-ink">{m.content}</p>
 {editing===m.id&&<div className="mt-3 flex gap-2"><input value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="Correct version" className="min-w-0 flex-1 rounded-xl border border-line bg-surface-subtle px-3 py-2 text-sm text-ink outline-none focus:border-accent"/><button onClick={()=>feedback(m,"correct",correction)} disabled={!correction.trim()} className="rounded-xl bg-accent px-3 text-xs font-semibold text-white disabled:opacity-40">Save</button><button onClick={()=>setEditing(null)} className="p-2 text-muted"><X size={15}/></button></div>}</div>
 <div className="flex shrink-0 gap-1"><button onClick={()=>feedback(m,"confirm")} title="Confirm" className="rounded-lg p-2 text-positive hover:bg-surface-subtle"><Check size={15}/></button><button onClick={()=>{setEditing(m.id);setCorrection(m.content)}} title="Correct" className="rounded-lg p-2 text-muted hover:bg-surface-subtle hover:text-ink"><Pencil size={15}/></button><button onClick={()=>feedback(m,"expire")} title="Expire" className="rounded-lg p-2 text-caution hover:bg-surface-subtle"><Clock size={15}/></button><button onClick={()=>feedback(m,"forget")} title="Forget" className="rounded-lg p-2 text-risk hover:bg-surface-subtle"><Trash2 size={15}/></button></div></div></article>)}</div>}</div></div>}
