"use client";
import { useCallback, useEffect, useState } from "react";
import { BellRing, CheckCircle2, Clock3, Loader2, Pause, Play, Plus, ShieldCheck, Workflow } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
type Rule={id:string;name:string;trigger_type:string;action_type:string;mode:string;enabled:boolean;last_run_at:string|null};
const templates=[
 {name:"Deadline approaching",trigger_type:"deadline_approaching",action_type:"surface_in_today",mode:"automatic"},
 {name:"Task becomes blocked",trigger_type:"task_blocked",action_type:"request_blocker_detail",mode:"suggest"},
 {name:"Coding Agent completes",trigger_type:"agent_completed",action_type:"create_review_request",mode:"approval_required"},
 {name:"Project becomes inactive",trigger_type:"project_inactive",action_type:"suggest_project_decision",mode:"suggest"},
 {name:"Weekly review",trigger_type:"weekly_boundary",action_type:"draft_weekly_review",mode:"automatic"},
];
export default function AutomationsPage(){const[rules,setRules]=useState<Rule[]>([]),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("automation_rules").select("*").eq("user_id",user.id).order("created_at");setRules(data??[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);
 async function add(t:typeof templates[number]){const{data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from("automation_rules").insert({user_id:user.id,...t,conditions:{},action_config:{}});load()}
 async function toggle(r:Rule){await supabase.from("automation_rules").update({enabled:!r.enabled,updated_at:new Date().toISOString()}).eq("id",r.id);load()}
 return <div className="flex-1 overflow-auto bg-canvas"><div className="mx-auto max-w-[960px] p-4 md:p-8"><header className="mb-6"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-accent">When → if → action</p><h1 className="mt-1 text-2xl font-semibold text-ink">Personal automations</h1><p className="mt-1 text-sm text-muted">Small reminders and drafts with visible approval boundaries.</p></header>
 <section className="mb-6"><h2 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted">Your rules</h2>{loading?<div className="flex gap-2 p-6 text-muted"><Loader2 className="animate-spin" size={15}/>Loading…</div>:rules.length===0?<div className="rounded-2xl border border-dashed border-line p-8 text-center text-sm text-muted">No automations enabled. Add a safe template below.</div>:<div className="space-y-2">{rules.map(r=><article key={r.id} className="flex items-center gap-3 rounded-2xl border border-line bg-surface p-4"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${r.enabled?"bg-accent-soft text-accent":"bg-surface-subtle text-faint"}`}><Workflow size={16}/></div><div className="min-w-0 flex-1"><h3 className="text-sm font-medium text-ink">{r.name}</h3><p className="mt-0.5 text-xs text-muted">{r.trigger_type.replaceAll("_"," ")} → {r.action_type.replaceAll("_"," ")}</p></div><span className={`hidden rounded-full px-2 py-1 text-[10px] font-semibold sm:inline ${r.mode==="approval_required"?"bg-accent-soft text-accent":"bg-surface-subtle text-muted"}`}>{r.mode.replaceAll("_"," ")}</span><button onClick={()=>toggle(r)} className="rounded-lg p-2 text-muted hover:bg-surface-subtle hover:text-ink">{r.enabled?<Pause size={15}/>:<Play size={15}/>}</button></article>)}</div>}</section>
 <section><h2 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted">Safe templates</h2><div className="grid gap-3 md:grid-cols-2">{templates.filter(t=>!rules.some(r=>r.trigger_type===t.trigger_type)).map((t,i)=>{const Icon=[Clock3,BellRing,ShieldCheck,Pause,CheckCircle2][i]??Workflow;return <button key={t.trigger_type} onClick={()=>add(t)} className="flex items-start gap-3 rounded-2xl border border-line bg-surface p-4 text-left hover:border-accent"><Icon size={16} className="mt-0.5 text-accent"/><div className="flex-1"><p className="text-sm font-medium text-ink">{t.name}</p><p className="mt-1 text-xs text-muted">{t.action_type.replaceAll("_"," ")} · {t.mode.replaceAll("_"," ")}</p></div><Plus size={15} className="text-faint"/></button>})}</div></section></div></div>}
