"use client";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Circle, Flag, Loader2, Plus, Target } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
type Goal={id:string;title:string;description:string|null;status:string;target_date:string|null;success_criteria:string|null;created_at:string};
export default function GoalsPage(){const[goals,setGoals]=useState<Goal[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[title,setTitle]=useState(""),[criteria,setCriteria]=useState(""),[date,setDate]=useState("");
 const load=useCallback(async()=>{setLoading(true);const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("goals").select("*").eq("user_id",user.id).neq("status","archived").order("created_at",{ascending:false});setGoals(data??[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);
 async function create(){if(!title.trim())return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from("goals").insert({user_id:user.id,title:title.trim(),success_criteria:criteria.trim()||null,target_date:date||null});setTitle("");setCriteria("");setDate("");setOpen(false);load()}
 async function toggle(g:Goal){const status=g.status==="completed"?"active":"completed";await supabase.from("goals").update({status,updated_at:new Date().toISOString()}).eq("id",g.id);load()}
 return <div className="flex-1 overflow-auto bg-canvas"><div className="mx-auto max-w-[920px] p-4 md:p-8"><header className="mb-6 flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-accent">Direction</p><h1 className="mt-1 text-2xl font-semibold text-ink">Goals</h1><p className="mt-1 text-sm text-muted">Connect daily work to outcomes that define done.</p></div><button onClick={()=>setOpen(!open)} className="flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-xs font-semibold text-white"><Plus size={14}/>New goal</button></header>
 {open&&<section className="mb-5 space-y-3 rounded-2xl border border-line bg-surface p-5"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Outcome to achieve" className="w-full rounded-xl border border-line bg-surface-subtle p-3 text-sm text-ink outline-none focus:border-accent"/><textarea value={criteria} onChange={e=>setCriteria(e.target.value)} placeholder="Completion criteria — how will you know it is done?" className="w-full rounded-xl border border-line bg-surface-subtle p-3 text-sm text-ink outline-none focus:border-accent"/><div className="flex flex-wrap gap-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-line bg-surface-subtle px-3 py-2 text-sm text-ink"/><button onClick={create} className="rounded-xl bg-accent px-4 py-2 text-xs font-semibold text-white">Create goal</button></div></section>}
 {loading?<div className="flex gap-2 p-8 text-sm text-muted"><Loader2 className="animate-spin" size={16}/>Loading goals…</div>:goals.length===0?<div className="rounded-2xl border border-dashed border-line p-12 text-center"><Target className="mx-auto text-faint"/><p className="mt-3 font-medium text-ink">No goals yet</p><p className="mt-1 text-sm text-muted">Start with one outcome—not a list of aspirations.</p></div>:<div className="space-y-3">{goals.map(g=><article key={g.id} className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-start gap-3"><button onClick={()=>toggle(g)} className={g.status==="completed"?"text-positive":"text-faint hover:text-positive"}>{g.status==="completed"?<CheckCircle2/>:<Circle/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><h2 className={`font-semibold ${g.status==="completed"?"text-muted line-through":"text-ink"}`}>{g.title}</h2>{g.target_date&&<span className="flex items-center gap-1 text-xs text-muted"><Flag size={12}/>{new Date(g.target_date+"T00:00:00").toLocaleDateString()}</span>}</div>{g.description&&<p className="mt-2 text-sm text-muted">{g.description}</p>}<div className="mt-4 rounded-xl bg-surface-subtle p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-faint">Completion criteria</p><p className="mt-1 text-sm text-ink">{g.success_criteria||"Not defined yet"}</p></div></div></div></article>)}</div>}</div></div>}
