"use client";
import { useEffect,useRef,useState } from "react";
import type { ChatContext,ChatMessage } from "@/lib/trading-lab/chat";
import { buttonClass,inputClass,labApi,panelClass } from "./manual-ui";
import { RecordFields,StrategyRules } from "./StrategyWorkspace";
export default function LabChat({context,onContext,onSaved,compact=false}:{context:ChatContext;onContext:(c:ChatContext)=>void;onSaved:(receipt?:any)=>Promise<void>;compact?:boolean}){
  const [sessions,setSessions]=useState<any[]>([]),[session,setSession]=useState<any>(null),[messages,setMessages]=useState<(ChatMessage&{request_id:string})[]>([]),[prompt,setPrompt]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[draftStatus,setDraftStatus]=useState(""),[research,setResearch]=useState(false);
  const newId=useRef<string>(""),pending=useRef<any>(null),active=useRef(0);
  const reloadSessions=async()=>setSessions((await labApi("chat")).sessions);
  const select=async(id:string)=>{const turn=++active.current;try{const data=await labApi(`chat?id=${encodeURIComponent(id)}`);if(turn!==active.current)return;setSession(data.session);setMessages(data.messages);setPrompt(data.session.lab_draft??"");onContext({strategyId:data.session.lab_context?.strategyId??null,strategyVersionId:data.session.lab_context?.strategyVersionId??null,experimentId:data.session.lab_context?.experimentId??null,paperRunId:data.session.lab_context?.paperRunId??null});localStorage.setItem("buddies.lab.session",id);setError("");}catch(e){if(turn===active.current)setError((e as Error).message);}};
  useEffect(()=>{newId.current=crypto.randomUUID();void reloadSessions().then(()=>{const id=localStorage.getItem("buddies.lab.session");if(id)void select(id);}).catch(e=>setError(e.message));return()=>{active.current++;};},[]);
  useEffect(()=>{if(!session||busy)return;setDraftStatus("Saving draft…");const timeout=setTimeout(()=>{void fetch("/api/trading-lab/chat",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:session.id,expectedRevision:session.lab_revision,draft:prompt})}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);setDraftStatus("Draft saved");}).catch(e=>setDraftStatus(`Draft not saved: ${e.message}`));},700);return()=>clearTimeout(timeout);},[prompt,session?.id,session?.lab_revision,busy]);
  const send=async(retry=false)=>{if(busy||(!retry&&!prompt.trim()))return;setBusy(true);setError("");const body=retry&&pending.current?pending.current:{sessionId:session?.id??newId.current,requestId:crypto.randomUUID(),expectedRevision:session?.lab_revision??0,prompt,context,research};pending.current=body;
    try{await labApi("chat",body);pending.current=null;await select(body.sessionId);await reloadSessions();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const approve=async(message:ChatMessage&{request_id:string})=>{setBusy(true);setError("");try{const r=await labApi("chat/actions",{sessionId:session.id,requestId:message.request_id,expectedRevision:session.lab_revision,approved:true});await select(session.id);await onSaved(r.receipt);}catch(e){setError((e as Error).message);await select(session.id);}finally{setBusy(false);}};
  const resumePending=()=>{const m=messages.find(m=>m.metadata?.status==="pending");const user=messages.find(x=>x.request_id===m?.request_id&&x.role==="user");if(!m||!user)return;pending.current={sessionId:session.id,requestId:m.request_id,expectedRevision:session.lab_revision,prompt:user.content,context:{strategyId:null,strategyVersionId:null,experimentId:null,paperRunId:null,...Object.fromEntries(Object.entries((user.metadata as any).context??context).filter(([k])=>k!=="research"))},research:(user.metadata as any).context?.research??false};void send(true);};
  return <section className={`${panelClass} ${compact?"lg:sticky lg:top-3":""}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-bold">Trading Lab chat</h2><p className="text-xs text-muted">Create, run and review strategies through saved records.</p></div><button disabled={busy} onClick={()=>{active.current++;newId.current=crypto.randomUUID();pending.current=null;setSession(null);setMessages([]);setPrompt("");setError("");localStorage.removeItem("buddies.lab.session");}} className="rounded-lg border border-line px-3 py-2 text-xs">New conversation</button></div>
    <select aria-label="Saved conversation" className={inputClass} value={session?.id??""} disabled={busy} onChange={e=>e.target.value&&void select(e.target.value)}><option value="">New conversation</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select>
    <div className={`mt-4 space-y-4 overflow-y-auto ${compact?"max-h-[55vh]":"max-h-[65vh] min-h-64"}`}>{!messages.length&&<p className="rounded-lg bg-surface-subtle p-4 text-sm text-muted">Describe your strategy, ask about an experiment, or tell Buddies what happened in a trade. The selected records above provide the working context.</p>}{messages.map(message=><article key={message.id} className={`rounded-xl p-3 text-sm ${message.role==="user"?"ml-5 bg-accent-soft":"bg-surface-subtle"}`}><p className="mb-2 text-xs font-semibold text-muted">{message.role==="user"?"You":"Buddies"}</p><p className="whitespace-pre-wrap leading-6">{message.content||"Response pending…"}</p>{message.metadata?.status==="pending"&&<button onClick={resumePending} disabled={busy} className="mt-2 text-accent">Recover pending response</button>}
      {(message.metadata as any)?.research?.citations?.length>0&&<ul className="mt-2 space-y-1 text-xs">{(message.metadata as any).research.citations.map((c:any,i:number)=><li key={i}><a href={/^https?:\/\//.test(c.url)?c.url:undefined} target="_blank" rel="noreferrer" className="text-accent underline">{c.title}</a></li>)}</ul>}
      {message.metadata?.action&&<div className="mt-3 rounded-lg border border-accent/30 bg-surface p-3"><p className="mb-3 font-bold">{message.metadata.status==="executed"?"Saved action":"Proposed action"} · {message.metadata.action.kind.replaceAll("_"," ")}</p><details open={!compact}><summary className="cursor-pointer text-xs font-semibold">Review exact details</summary><div className="mt-3">{message.metadata.action.kind==="save_strategy"?<StrategyRules definition={message.metadata.action.input.definition}/>:<RecordFields value={message.metadata.action.input}/>}</div></details>{message.metadata.status==="executed"?<p className="mt-3 text-xs text-emerald-600">Saved receipt confirmed. The corresponding records are available in the tabs.</p>:<button onClick={()=>void approve(message)} disabled={busy||(message.sequence!==session?.lab_revision&&!["executing","action_failed"].includes(message.metadata.status??""))} className={`${buttonClass} mt-3`}>{["executing","action_failed"].includes(message.metadata.status??"")?"Recover / retry this action":"Approve this exact action"}</button>}{message.metadata.error&&<p className="mt-2 text-xs text-amber-600">{message.metadata.error}</p>}</div>}
    </article>)}</div>
    {error&&<div role="alert" className="mt-3 rounded-lg border border-amber-500/40 p-3 text-sm text-amber-600">{error}{pending.current&&<button disabled={busy} onClick={()=>void send(true)} className="ml-2 underline">Retry saved request</button>}</div>}
    <form onSubmit={e=>{e.preventDefault();void send();}}><label className="mt-3 flex items-center gap-2 text-xs text-muted"><input type="checkbox" checked={research} disabled={busy} onChange={e=>setResearch(e.target.checked)}/>Include web research with sources</label><textarea aria-label="Message Buddies" value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={busy} maxLength={8000} className={`${inputClass} mt-4 min-h-28`} placeholder="Describe a strategy, revise a rule, prepare a paper sample, or review a result…"/><div className="mt-2 flex items-center justify-between gap-2"><p className="text-[11px] text-muted">{session?draftStatus:"Conversation saves when you send."}</p><button className={buttonClass} disabled={busy||!prompt.trim()}>{busy?"Working…":"Send"}</button></div></form>
  </section>;
}
