"use client";
import { FormEvent, useEffect, useState } from "react";
import { behaviorTypes, reviewQuestions } from "@/lib/trading-lab/lifecycle";
import { buttonClass, Field, formValues, inputClass, labApi, localTime, panelClass, TextField, useRequestIdentity } from "./manual-ui";

const labels: Record<string, string> = { thesis: "Market thesis correct", direction: "Direction correct", entryTiming: "Entry timing correct", confirmation: "Confirmation valid", stopPlacement: "SL placement correct", targetRealistic: "TP realistic", strategyFollowed: "Strategy followed", managementFollowed: "Position management followed the plan" };
export default function ManualTrades({source,reviewsOnly=false}:{source?:"broker_manual";reviewsOnly?:boolean}) {
  const [trades, setTrades] = useState<any[]>([]), [plans, setPlans] = useState<any[]>([]), [rules, setRules] = useState<any[]>([]);
  const [selected, setSelected] = useState(""), [planId, setPlanId] = useState(""), [events, setEvents] = useState<any[]>([]);
  const [kind, setKind] = useState("change_protection"), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const identity = useRequestIdentity();
  const trade = trades.find(t => t.id === selected), plan = plans.find(p => p.id === planId);
  const reload = async (id = selected) => {
    const [data, saved] = await Promise.all([labApi("trades"), labApi("plans")]); setTrades(source?data.trades.filter((t:any)=>t.execution_source!=="paper"):data.trades); setRules(data.rules); setPlans(saved.plans);
    if (id) setEvents((await labApi(`trades?tradeId=${encodeURIComponent(id)}`)).events);
  };
  useEffect(() => { void reload().catch(e => setMessage(e.message)); }, []);
  useEffect(() => { let active = true; setEvents([]); if (selected) void labApi(`trades?tradeId=${encodeURIComponent(selected)}`).then(d => { if (active) setEvents(d.events); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, [selected]);
  const save = async (payload: any, eventKind: string, target?: any) => {
    const body = { tradeId: target?.id ?? identity({ openPlan: payload.planId }), expectedRevision: target?.lifecycle_revision ?? 0, kind: eventKind, payload };
    const saved = await labApi("trades", { ...body, requestId: identity(body) });
    setSelected(saved.trade.id); await reload(saved.trade.id); setMessage(eventKind === "review" ? "Review saved to shared decisions, lessons, behavior and memory." : "Execution record saved.");
  };
  const open = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const v = formValues(event.currentTarget); setBusy(true); setMessage("");
    try { await save({ planId, accountType: v.text("accountType"), occurredAt: v.time("occurredAt"), price: v.number("price"), quantity: v.number("quantity"), stopLoss: v.number("stopLoss"), takeProfit: v.number("takeProfit"), actualRiskAmount: v.number("actualRiskAmount"), brokerReference: v.text("brokerReference"), reason: v.text("reason") }, "open"); setPlanId(""); }
    catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  };
  const execution = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const v = formValues(event.currentTarget); setBusy(true); setMessage("");
    try {
      const payload = { occurredAt: v.time("occurredAt"), reason: v.text("reason"),
        ...(kind === "change_protection" ? { stopLoss: v.number("stopLoss"), takeProfit: v.number("takeProfit") } : { price: v.number("price"), quantity: v.number("quantity") }),
        ...(kind === "close" ? { pnlAmount: v.number("pnlAmount"), pnlBasis: v.text("pnlBasis"), fees: v.number("fees"), financing: v.number("financing"), pnlEvidence: v.text("pnlEvidence") } : {}) };
      await save(payload, kind, trade);
    } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  };
  const review = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const v = formValues(event.currentTarget); setBusy(true); setMessage("");
    try {
      const reference = (key: string) => ({ r: v.text(`${key}.r`) === "" ? null : v.number(`${key}.r`), evidence: v.text(`${key}.evidence`) });
      const payload = { findings: Object.fromEntries(reviewQuestions.map(k => [k, { status: v.text(`${k}.status`), evidence: v.text(`${k}.evidence`) }])),
        strategyReference: reference("strategyReference"), frozenPlanReference: reference("frozenPlanReference"),
        probabilityOutcome: v.text("probabilityOutcome"), probabilityObservedAt: v.text("probabilityObservedAt") ? v.time("probabilityObservedAt") : null, probabilityEvidence: v.text("probabilityEvidence"),
        behaviors: behaviorTypes.filter(k => v.checked(k)).map(type => ({ type, evidence: v.text(`${type}.evidence`), ruleId: v.text(`${type}.ruleId`) || null })),
        lesson: v.text("lesson"), nextAction: v.text("nextAction") };
      await save(payload, "review", trade);
    } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  };
  return <div className="space-y-4">
    <section className={panelClass}><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Manual execution and review</h2><p className="mt-1 text-sm text-muted">Record what actually happened with your broker. Original plans and event history stay intact.</p></div><button onClick={() => void reload().catch(e => setMessage(e.message))} className="rounded-lg border border-line px-3 py-2 text-sm">Refresh</button></div></section>
    {!reviewsOnly&&<section className={panelClass}><h3 className="font-semibold">Record an executed plan</h3><label className="mt-3 block text-xs text-muted">Locked pre-trade plan<select value={planId} onChange={e => setPlanId(e.target.value)} className={inputClass}><option value="">Choose a plan</option>{plans.filter(p => !trades.some(t => t.decision_id === p.id && t.execution_source!=="paper")).map(p => <option key={p.id} value={p.id}>{p.plan_snapshot.instrument} · {p.plan_snapshot.direction} · {new Date(p.locked_at).toLocaleString()} · {p.assessment_snapshot.verdict}</option>)}</select></label>
      {plan && <form key={planId} onSubmit={open} className="mt-4"><fieldset disabled={busy} className="space-y-3"><p className="text-sm">Planned entry {plan.plan_snapshot.entry} · SL {plan.plan_snapshot.stopLoss} · TP {plan.plan_snapshot.takeProfit} · {plan.plan_snapshot.quantity} {plan.plan_snapshot.quantityUnit} · risk {plan.plan_snapshot.riskAmount} {plan.plan_snapshot.riskCurrency}</p>
        <p className="text-xs text-muted">Copy actual values from the broker. Execution before this plan was locked or after its expiry is flagged during review. Deviations remain part of the sample.</p>
        <label className="block text-xs text-muted">Actual account type<select name="accountType" required defaultValue="" className={inputClass}><option value="" disabled>Choose live or demo</option><option value="live">Live · real money</option><option value="demo">Demo · simulated money</option></select></label><p className="text-xs text-muted">A trade from a different account type is recorded outside the experiment's sample.</p>
        <div className="grid gap-3 sm:grid-cols-3"><Field name="occurredAt" label="Actual opening time · local time" type="datetime-local"/><Field name="price" label="Actual initial entry" type="number" min={0.000001}/><Field name="quantity" label={`Actual initial quantity · ${plan.plan_snapshot.quantityUnit}`} type="number" min={0.000001}/><Field name="stopLoss" label="Actual initial SL" type="number" min={0.000001}/><Field name="takeProfit" label="Actual initial TP" type="number" min={0.000001}/><Field name="actualRiskAmount" label={`Actual initial monetary risk · ${plan.plan_snapshot.riskCurrency}`} type="number" min={0.01}/><Field name="brokerReference" label="Broker / account / ticket reference"/></div>
        <TextField name="reason" label="Execution evidence and reasons for any deviation"/><button className={buttonClass}>Record actual entry</button>
      </fieldset></form>}
    </section>
    }
    {message && <p role="status" className="rounded-lg border border-line p-3 text-sm">{message}</p>}
    <section className={panelClass}><h3 className="font-semibold">Recorded trades</h3><label className="mt-3 block text-xs text-muted">Trade<select value={selected} onChange={e => setSelected(e.target.value)} className={inputClass}><option value="">Choose a recorded trade</option>{[...trades].sort((a, b) => b.opened_at.localeCompare(a.opened_at)).map(t => <option key={t.id} value={t.id}>{t.execution_source==="paper"?"Paper":"Broker"} · {t.instrument} · {new Date(t.opened_at).toLocaleString()} · {t.status} · {t.net_pnl == null ? "unrealized" : `${t.net_pnl} ${t.risk_currency}`} {t.experiment_id && !t.sample_member ? "· outside sample" : ""}</option>)}</select></label>
      {!trades.length && <p className="mt-3 text-sm text-muted">No manual lifecycle trades yet. Historical CSV and quick entries remain in Journal.</p>}
    </section>
    {trade && <>
      <section className={panelClass}><h3 className="font-semibold">Prediction → plan → execution → outcome</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Measure</th><th className="p-2">Frozen plan</th><th className="p-2">Recorded execution</th></tr></thead><tbody>
        {[["Entry", trade.plan_snapshot.entry, trade.entry_price], ["Initial SL", trade.plan_snapshot.stopLoss, trade.open_snapshot.stopLoss], ["Initial TP", trade.plan_snapshot.takeProfit, trade.open_snapshot.takeProfit], ["Initial quantity", trade.plan_snapshot.quantity, trade.open_snapshot.quantity], ["Initial monetary risk", `${trade.plan_snapshot.riskAmount} ${trade.risk_currency}`, `${trade.open_snapshot.actualRiskAmount} ${trade.risk_currency}`], ["Final average exit", trade.plan_snapshot.takeProfit, trade.exit_price ?? "Open"], ["Net realized result", "Unknown until observed", trade.net_pnl == null ? "Open" : `${trade.net_pnl} ${trade.risk_currency} / ${Number(trade.net_pnl / trade.planned_risk_amount).toFixed(3)}R`]].map(([label, planned, actual]) => <tr key={label} className="border-t border-line"><td className="p-2 text-muted">{label}</td><td className="p-2">{planned}</td><td className="p-2">{actual}</td></tr>)}
      </tbody></table></div><p className="mt-2 text-xs text-muted">Probability: {trade.plan_snapshot.predictedProbability == null ? "unknown" : `${trade.plan_snapshot.predictedProbability}% (uncalibrated)`} for TP before SL by {new Date(trade.plan_snapshot.validUntil).toLocaleString()}. Remaining: {trade.remaining_quantity} {trade.plan_snapshot.quantityUnit}.</p>
        <p className="mt-2 text-xs text-muted">Plan recorded: {new Date(trade.locked_at).toLocaleString()} · broker opening: {new Date(trade.opened_at).toLocaleString()}. {new Date(trade.opened_at) < new Date(trade.locked_at) ? "Flag: execution predates the saved plan." : new Date(trade.opened_at) >= new Date(trade.plan_snapshot.validUntil) ? "Flag: execution occurred after plan expiry." : "Reported opening is within the saved window; broker evidence remains manual."}</p>
        <details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">Recorded thesis and evidence</summary><p className="mt-2 whitespace-pre-wrap text-sm">{trade.plan_snapshot.context}</p>{trade.plan_snapshot.marketContext && <dl className="mt-2 space-y-2 text-xs">{Object.entries(trade.plan_snapshot.marketContext).filter(([, v]) => v).map(([key, value]) => <div key={key}><dt className="font-semibold">{key}</dt><dd>{String(value)}</dd></div>)}</dl>}{trade.plan_snapshot.evidenceLinks?.map((link: string) => <a key={link} href={link} target="_blank" rel="noreferrer" className="mt-2 block break-all text-xs text-accent">{link}</a>)}</details>
      </section>
      {trade.status === "open" && trade.execution_source!=="paper" && <section className={panelClass}><h3 className="font-semibold">Record the next execution event</h3><label className="mt-3 block text-xs text-muted">Event<select value={kind} onChange={e => setKind(e.target.value)} className={inputClass}><option value="change_protection">SL / TP change</option><option value="add_fill">Additional entry fill (before any exit)</option><option value="partial_exit">Partial exit</option><option value="close">Final exit and reconciliation</option></select></label>
        <form key={`${trade.id}:${kind}:${trade.lifecycle_revision}`} onSubmit={execution} className="mt-3"><fieldset disabled={busy} className="space-y-3"><div className="grid gap-3 sm:grid-cols-3"><Field name="occurredAt" label="Actual event time · local time" type="datetime-local"/>
          {kind === "change_protection" ? <><Field name="stopLoss" label="New SL" type="number" min={0.000001}/><Field name="takeProfit" label="New TP" type="number" min={0.000001}/></> : <><Field name="price" label="Actual fill price" type="number" min={0.000001}/><Field name="quantity" label={`Fill quantity · ${trade.plan_snapshot.quantityUnit}`} type="number" value={kind === "close" ? trade.remaining_quantity : undefined} min={0.000001}/></>}
        </div><TextField name="reason" label="Reason / evidence for this event"/>
        {kind === "close" && <><p className="rounded-lg bg-surface-subtle p-3 text-sm">Reconcile P&L for the entire trade, including all partial exits. R uses the original planned monetary risk. Enter fees and financing in {trade.risk_currency}.</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-muted">P&L basis<select name="pnlBasis" className={inputClass}><option value="broker_net">Broker net · already includes all costs</option><option value="gross">Gross · subtract fees and add signed financing</option></select></label><Field name="pnlAmount" label="Total trade P&L" type="number"/><Field name="fees" label="Total fees · positive cost" type="number" min={0}/><Field name="financing" label="Financing · negative charge / positive credit" type="number"/></div><TextField name="pnlEvidence" label="Broker statement / reconciliation evidence"/><p className="text-xs text-muted">With broker net, fees and financing are recorded for reference and are not applied again.</p></>}
        <button className={buttonClass}>{kind === "close" ? "Save final exit & close trade" : "Save execution event"}</button></fieldset></form>
      </section>}
      {trade.status === "closed" && <section className={panelClass}><h3 className="font-semibold">Post-trade evidence review</h3><p className="mt-2 text-sm text-muted">Judge methodology, execution and behavior separately. A losing trade can have correct execution. Leave conclusions unknown when the evidence is missing.</p>
        <form key={`${trade.id}:${trade.lifecycle_revision}`} onSubmit={review} className="mt-4"><fieldset disabled={busy} className="space-y-4">
          {reviewQuestions.map(key => <div key={key} className="grid gap-2 rounded-lg border border-line p-3 sm:grid-cols-[1fr_150px]"><label htmlFor={key} className="text-sm font-medium">{labels[key]}</label><select id={key} name={`${key}.status`} defaultValue={trade.review_snapshot?.findings[key]?.status ?? "unknown"} className={inputClass}><option value="unknown">Unknown</option><option value="pass">Yes / followed</option><option value="fail">No / violated</option></select><input name={`${key}.evidence`} aria-label={`Evidence for ${labels[key]}`} defaultValue={trade.review_snapshot?.findings[key]?.evidence ?? ""} placeholder="Evidence supporting this finding" maxLength={2000} className={`${inputClass} sm:col-span-2`}/></div>)}
          <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer font-semibold">Behavioral interference and existing rules</summary><div className="mt-3 space-y-3">{behaviorTypes.map(type => { const prior = trade.review_snapshot?.behaviors.find((b: any) => b.type === type); return <div key={type} className="rounded-lg bg-surface-subtle p-3"><label className="flex gap-2 text-sm"><input name={type} type="checkbox" defaultChecked={Boolean(prior)}/>{type.replaceAll("_", " ")}</label><input name={`${type}.evidence`} defaultValue={prior?.evidence} aria-label={`Evidence for ${type}`} placeholder="What happened? Evidence is required when selected." className={inputClass}/><label className="mt-2 block text-xs text-muted">Link an existing Buddies rule · optional<select name={`${type}.ruleId`} defaultValue={prior?.ruleId ?? ""} className={inputClass}><option value="">Behavior observation only</option>{rules.map(r => <option key={r.id} value={r.id}>{r.rule_text}</option>)}</select></label></div>; })}</div></details>
          <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer font-semibold">Reference outcomes · optional, evidence required</summary><p className="mt-2 text-xs text-muted">Use the same original risk baseline and net cost basis as actual R. A strategy reference follows the methodology; a frozen-plan reference follows the exact saved entry and exits. These are manual reconstructions, not automatically verified counterfactuals.</p><div className="mt-3 space-y-3">{[["strategyReference", "Strategy reference"], ["frozenPlanReference", "Frozen plan"]].map(([key, label]) => <div key={key}><Field name={`${key}.r`} label={`${label} outcome · net R`} type="number" required={false} value={trade.review_snapshot?.[key]?.r ?? ""}/><TextField name={`${key}.evidence`} label={`${label} reconstruction evidence, timestamps and cost assumptions`} required={false} value={trade.review_snapshot?.[key]?.evidence}/></div>)}</div></details>
          <div className="space-y-3 rounded-lg border border-line p-3"><h4 className="font-semibold">Resolve the original prediction</h4><p className="text-xs text-muted">Did TP occur before SL under the frozen plan by {new Date(trade.plan_snapshot.validUntil).toLocaleString()}? An early actual exit does not answer this question.</p><label className="block text-xs text-muted">Observed event<select name="probabilityOutcome" defaultValue={trade.review_snapshot?.probabilityOutcome ?? "unresolved"} className={inputClass}><option value="unresolved">Unresolved / insufficient evidence</option><option value="target_first">TP first, within the horizon</option><option value="stop_first">SL first, within the horizon</option><option value="neither">Neither by expiry</option></select></label><Field name="probabilityObservedAt" label="Event time (or observation through expiry) · local time" type="datetime-local" required={false} value={trade.review_snapshot?.probabilityObservedAt ? localTime(Date.parse(trade.review_snapshot.probabilityObservedAt)) : ""}/><TextField name="probabilityEvidence" label="Chart / market path evidence" required={false} value={trade.review_snapshot?.probabilityEvidence}/></div>
          <TextField name="lesson" label="Evidence-backed lesson" value={trade.review_snapshot?.lesson}/><TextField name="nextAction" label="What should change for the next decision or sample?" value={trade.review_snapshot?.nextAction}/>
          <button className={buttonClass}>{trade.review_snapshot ? "Append amended review" : "Save review & learning"}</button><p className="text-xs text-muted">Saved reviews enter Buddies’ shared learning and memory. Amendments preserve earlier evidence. Finalized experiment samples cannot be rewritten.</p>
        </fieldset></form>
      </section>}
      <section className={panelClass}><h3 className="font-semibold">Execution and review history</h3><ol className="mt-3 space-y-3">{events.map(e => <li key={e.id} className="rounded-lg border border-line p-3 text-sm"><p className="font-semibold">{e.kind.replaceAll("_", " ")} · recorded {new Date(e.recorded_at).toLocaleString()}</p>{e.payload.occurredAt && <p className="mt-1 text-xs text-muted">Actual event: {new Date(e.payload.occurredAt).toLocaleString()}{e.payload.price ? ` · price ${e.payload.price} · quantity ${e.payload.quantity}` : ` · SL ${e.payload.stopLoss} · TP ${e.payload.takeProfit}`}</p>}<p className="mt-1 whitespace-pre-wrap">{e.payload.reason ?? e.payload.lesson}</p></li>)}</ol></section>
    </>}
  </div>;
}
