"use client";
import { strategyCapabilities } from "@/lib/trading-lab/paper-contracts";
import { validateStrategyVersion } from "@/lib/trading-lab/strategy-schema";
import ManualStrategyEditor from "./ManualStrategyEditor";
import { panelClass } from "./manual-ui";
export function RecordFields({value}:{value:any}){if(value===null||value===undefined)return <span className="text-muted">Unknown</span>;if(typeof value!=="object")return <span className="whitespace-pre-wrap break-words">{String(value)}</span>;if(Array.isArray(value))return <ul className="list-inside list-disc space-y-1">{value.map((v,i)=><li key={i}><RecordFields value={v}/></li>)}</ul>;return <dl className="space-y-2">{Object.entries(value).filter(([k])=>!["requestId","approved","schemaVersion"].includes(k)).map(([key,v])=><div key={key} className="grid gap-1 border-b border-line/50 pb-2 sm:grid-cols-[150px_minmax(0,1fr)]"><dt className="font-medium capitalize text-muted">{key.replace(/([A-Z])/g," $1")}</dt><dd className="min-w-0"><RecordFields value={v}/></dd></div>)}</dl>;}
export function StrategyRules({definition}:{definition:any}){return <div className="space-y-3 text-sm"><h3 className="text-lg font-bold">{definition.name}</h3><p className="text-muted">{definition.description}</p><RecordFields value={Object.fromEntries(Object.entries(definition).filter(([k])=>!["name","description"].includes(k)))}/></div>;}
export default function StrategyWorkspace({strategies,versionId,implementation,onSaved}:{strategies:any[];versionId:string|null;implementation:boolean;onSaved:()=>Promise<void>}){
  const family=strategies.find(s=>s.trading_strategy_versions?.some((v:any)=>v.id===versionId));const version=family?.trading_strategy_versions.find((v:any)=>v.id===versionId);const parsed=validateStrategyVersion(version?.definition);
  if(implementation)return <section className={panelClass}><h2 className="text-xl font-bold">Strategy implementation</h2><p className="mt-2 text-sm text-muted">Every rule below belongs to the selected saved version. Manual and unsupported requirements block rule-driven paper execution.</p>{parsed.success?<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-line"><th className="p-2">Rule</th><th className="p-2">Implementation</th><th className="p-2">Evidence and limitations</th></tr></thead><tbody>{strategyCapabilities(parsed.data).map(r=><tr key={r.key} className="border-b border-line"><td className="p-2">{r.label}</td><td className={`p-2 font-semibold ${r.status==="automatic"?"text-emerald-600":"text-amber-600"}`}>{r.status}</td><td className="p-2 text-muted">{r.detail}</td></tr>)}</tbody></table></div>:<p className="mt-4 text-sm">Select a valid saved strategy version above.</p>}</section>;
  const previous=family?.trading_strategy_versions.filter((v:any)=>v.version<version.version).sort((a:any,b:any)=>b.version-a.version)[0];
  const changed=previous?Object.keys(version.definition).filter(k=>JSON.stringify(version.definition[k])!==JSON.stringify(previous.definition[k])):[];
  return <div className="space-y-4">{version?<section className={panelClass}><p className="mb-3 text-xs text-muted">Saved version {version.version} · {version.change_note}</p><StrategyRules definition={version.definition}/>{previous&&<details className="mt-4 rounded-lg border border-line p-3"><summary className="cursor-pointer font-semibold">Changes since v{previous.version}: {changed.join(", ")||"No rule changes"}</summary><div className="mt-3 grid gap-4 lg:grid-cols-2"><div><p className="mb-2 font-bold">Previous</p><RecordFields value={Object.fromEntries(changed.map(k=>[k,previous.definition[k]]))}/></div><div><p className="mb-2 font-bold">Selected</p><RecordFields value={Object.fromEntries(changed.map(k=>[k,version.definition[k]]))}/></div></div></details>}</section>:<section className={panelClass}><p>Select a version above, describe your strategy in chat, or use the editor below.</p></section>}<ManualStrategyEditor strategies={strategies} onSaved={onSaved}/></div>;
}
