"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, Bot, Cable, ChevronRight, FlaskConical, LineChart, Loader2, RefreshCw, ShieldCheck, Upload, WalletCards } from "lucide-react";

type AnyMap = Record<string, any>;
const tabs = ["Decision", "Strategies", "Backtest", "Ladder", "Journal", "Connectors"] as const;

async function api(path: string, init?: RequestInit) {
  const response = await fetch(path, init);
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || "Request failed");
  return data;
}

function Sparkline({ values, color = "#d6a84b" }: { values: number[]; color?: string }) {
  const points = useMemo(() => {
    if (!values.length) return "";
    const min = Math.min(...values), max = Math.max(...values), span = max - min || 1;
    return values.map((value, index) => `${(index / Math.max(values.length - 1, 1)) * 100},${38 - ((value - min) / span) * 34}`).join(" ");
  }, [values]);
  return <svg viewBox="0 0 100 40" preserveAspectRatio="none" className="h-48 w-full"><defs><linearGradient id="labfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><polygon points={`0,40 ${points} 100,40`} fill="url(#labfill)"/><polyline points={points} fill="none" stroke={color} strokeWidth="1.2" vectorEffect="non-scaling-stroke"/></svg>;
}

function Pillar({ title, data }: { title: string; data?: AnyMap }) {
  const bias = data?.bias ?? "unavailable";
  const tone = bias === "bullish" ? "text-emerald-500" : bias === "bearish" ? "text-red-500" : "text-muted";
  return <article className="rounded-xl border border-line bg-surface-subtle p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-muted">{title}</p><span className={`text-xs font-bold uppercase ${tone}`}>{bias}</span></div><p className="mt-3 text-sm font-semibold leading-5">{data?.summary ?? "Run the decision engine"}</p><p className="mt-2 text-xs text-muted">Confidence {data?.confidence ?? 0}%</p>{data?.warnings?.[0] && <p className="mt-2 text-xs text-amber-500">{data.warnings[0]}</p>}</article>;
}

export default function TradingLabDashboard() {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Decision");
  const [market, setMarket] = useState<AnyMap | null>(null), [strategies, setStrategies] = useState<AnyMap | null>(null), [connectors, setConnectors] = useState<any[]>([]);
  const [backtest, setBacktest] = useState<AnyMap | null>(null), [ladder, setLadder] = useState<AnyMap | null>(null), [decision, setDecision] = useState<AnyMap | null>(null), [journal, setJournal] = useState<AnyMap>({ entries: [] });
  const [templateId, setTemplateId] = useState("swing"), [capital, setCapital] = useState(10000), [risk, setRisk] = useState(1), [ladderPreset, setLadderPreset] = useState("steady");
  const [busy, setBusy] = useState(""), [notice, setNotice] = useState(""), [copilot, setCopilot] = useState(""), [prompt, setPrompt] = useState("");

  const load = async () => {
    setBusy("load"); setNotice("");
    const results = await Promise.allSettled([api("/api/trading-lab/market"), api("/api/trading-lab/strategies"), api("/api/trading-lab/connectors"), api("/api/trading-lab/journal")]);
    if (results[0].status === "fulfilled") setMarket(results[0].value);
    if (results[1].status === "fulfilled") setStrategies(results[1].value);
    if (results[2].status === "fulfilled") setConnectors(results[2].value.connectors ?? []);
    if (results[3].status === "fulfilled") setJournal(results[3].value);
    if (results.some(item => item.status === "rejected")) setNotice("Some saved-data features need the Trading Lab migration. Research tools remain available in demo mode.");
    setBusy("");
  };
  useEffect(() => { void load(); }, []);

  const runDecision = async () => { try { setBusy("decision"); setDecision(await api("/api/trading-lab/decision", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ symbol: "XAU/USD" }) })); } catch (e) { setNotice((e as Error).message); } finally { setBusy(""); } };
  const runTest = async () => { try { setBusy("backtest"); const data = await api("/api/trading-lab/strategies", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "backtest", templateId, initialCapital: capital, riskPct: risk, ladderPreset }) }); setBacktest(data); setTab("Backtest"); } catch (e) { setNotice((e as Error).message); } finally { setBusy(""); } };
  const simulate = async () => { if (!backtest) return; try { setBusy("ladder"); const data = await api("/api/trading-lab/ladder", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "simulate", presetId: ladderPreset, startingBalance: capital, trades: backtest.result.trades }) }); setLadder(data); setTab("Ladder"); } catch (e) { setNotice((e as Error).message); } finally { setBusy(""); } };
  const askCopilot = async () => { if (!prompt.trim()) return; try { setBusy("ai"); const data = await api("/api/trading-lab/copilot", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt, backtest: backtest?.result?.metrics }) }); setCopilot(data.content); } catch (e) { setCopilot(`AI unavailable: ${(e as Error).message}`); } finally { setBusy(""); } };
  const uploadCsv = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { setBusy("csv"); const data = await api("/api/trading-lab/journal", { method: "POST", body: form }); setNotice(`Imported ${data.imported}; skipped ${data.skipped}.`); await load(); } catch (e) { setNotice((e as Error).message); } finally { setBusy(""); } };

  const snapshot = decision?.snapshot ?? market;
  return <main className="min-h-screen bg-canvas px-3 py-4 text-ink sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-4">
    <header className="rounded-2xl border border-line bg-surface p-5 shadow-panel"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="rounded-full bg-amber-500/15 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-amber-500">{snapshot?.demo ? "Demo data" : "Live data"}</span><span className="text-xs text-muted">Research only · no broker execution</span></div><h1 className="mt-3 text-2xl font-bold sm:text-3xl">Gold Trading Lab</h1><p className="mt-1 text-sm text-muted">Evidence, repeatable rules, deterministic tests and an auditable decision journal.</p></div><div className="text-right"><p className="text-xs text-muted">XAU / USD</p><p className="mt-1 text-2xl font-bold tabular-nums">{snapshot?.currentPrice ? `$${Number(snapshot.currentPrice).toLocaleString()}` : "—"}</p><button onClick={load} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-accent"><RefreshCw size={13}/> Refresh</button></div></div></header>
    {notice && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-500">{notice}</div>}
    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-line bg-surface p-1">{tabs.map(item => <button key={item} onClick={() => setTab(item)} className={`shrink-0 rounded-lg px-4 py-2 text-xs font-bold ${tab === item ? "bg-accent text-white" : "text-muted hover:bg-surface-subtle"}`}>{item}</button>)}</nav>

    {tab === "Decision" && <div className="grid gap-4 lg:grid-cols-[1.45fr_.55fr]"><section className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-muted">Completed-candle view</p><h2 className="mt-1 text-lg font-bold">XAU/USD price structure</h2></div><span className="text-xs text-muted">{snapshot?.source ?? "Loading"}</span></div><Sparkline values={(snapshot?.candles ?? []).map((item: AnyMap) => item.close)}/><div className="grid gap-3 sm:grid-cols-3"><Pillar title="Fundamental" data={snapshot?.fundamental}/><Pillar title="Technical" data={snapshot?.technical}/><Pillar title="Volume / Wyckoff" data={snapshot?.volume}/></div></section><aside className="space-y-4"><section className="rounded-2xl border border-line bg-surface p-5"><p className="text-xs font-bold uppercase tracking-wider text-muted">Decision state</p><h2 className="mt-3 text-xl font-black">{snapshot?.decision?.state ?? "NOT RUN"}</h2><p className="mt-3 text-sm leading-6 text-muted">{decision?.narrative ?? snapshot?.decision?.trigger ?? "Run the engine to create an evidence-grounded view."}</p>{snapshot?.decision?.blockers?.map((item: string) => <p key={item} className="mt-2 text-xs text-amber-500">• {item}</p>)}<button onClick={runDecision} disabled={!!busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy === "decision" ? <Loader2 className="animate-spin" size={16}/> : <Activity size={16}/>} Run decision</button></section><section className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center gap-2"><Bot size={16} className="text-accent"/><p className="text-sm font-bold">Strategy Copilot</p></div><textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="Turn my idea into measurable rules…" className="mt-3 min-h-24 w-full rounded-lg border border-line bg-canvas p-3 text-sm outline-none focus:border-accent"/><button onClick={askCopilot} className="mt-2 text-xs font-bold text-accent">Ask Copilot</button>{copilot && <p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-muted">{copilot}</p>}</section></aside></div>}

    {tab === "Strategies" && <section className="grid gap-4 md:grid-cols-3">{Object.entries(strategies?.templates ?? {}).map(([id, item]: [string, any]) => <article key={id} className={`rounded-2xl border bg-surface p-5 ${templateId === id ? "border-accent" : "border-line"}`}><FlaskConical size={20} className="text-accent"/><h2 className="mt-4 font-bold">{item.name}</h2><p className="mt-2 min-h-12 text-xs leading-5 text-muted">{item.description}</p><div className="mt-4 space-y-2 text-xs"><p>Context <b>{item.timeframes.context.join(" · ")}</b></p><p>Trigger <b>{item.timeframes.trigger}</b></p><p>Risk <b>{item.sizing.value}%</b> · Target <b>{item.exit.targetValue}R</b></p></div><button onClick={() => setTemplateId(id)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg border border-line px-3 py-2 text-xs font-bold">Select <ChevronRight size={14}/></button></article>)}</section>}

    {tab === "Backtest" && <div className="grid gap-4 lg:grid-cols-[.35fr_.65fr]"><section className="rounded-2xl border border-line bg-surface p-5"><h2 className="font-bold">Test configuration</h2><label className="mt-4 block text-xs text-muted">Strategy<select value={templateId} onChange={e => setTemplateId(e.target.value)} className="mt-1 w-full rounded-lg border border-line bg-canvas p-2.5 text-sm text-ink">{Object.entries(strategies?.templates ?? {}).map(([id, item]: [string, any]) => <option key={id} value={id}>{item.name}</option>)}</select></label><label className="mt-3 block text-xs text-muted">Starting capital<input type="number" value={capital} onChange={e => setCapital(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-line bg-canvas p-2.5 text-sm text-ink"/></label><label className="mt-3 block text-xs text-muted">Risk per trade %<input type="number" step=".25" value={risk} onChange={e => setRisk(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-line bg-canvas p-2.5 text-sm text-ink"/></label><label className="mt-3 block text-xs text-muted">Risk overlay<select value={ladderPreset} onChange={e => setLadderPreset(e.target.value)} className="mt-1 w-full rounded-lg border border-line bg-canvas p-2.5 text-sm text-ink"><option value="steady">Fixed risk</option><option value="controlled">Capped progression</option></select></label><button onClick={runTest} className="mt-5 flex w-full justify-center rounded-lg bg-accent py-2.5 text-sm font-bold text-white">Run deterministic test</button></section><section className="rounded-2xl border border-line bg-surface p-5">{backtest ? <><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Net return", `${backtest.result.metrics.netReturnPct}%`],["Win rate", `${backtest.result.metrics.winRate}%`],["Profit factor", backtest.result.metrics.profitFactor ?? "—"],["Max drawdown", `${backtest.result.metrics.maxDrawdownPct}%`]].map(([label,value]) => <div key={label} className="rounded-xl bg-surface-subtle p-3"><p className="text-xs text-muted">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>)}</div><Sparkline values={backtest.result.equityCurve.map((item: AnyMap) => item.balance)} color="#3b82f6"/><div className="flex items-center justify-between text-xs text-muted"><span>{backtest.result.metrics.totalTrades} simulated trades · {backtest.dataset.demo ? "demo dataset" : backtest.dataset.source}</span><button onClick={simulate} className="font-bold text-accent">Send to ladder →</button></div></> : <div className="flex h-80 flex-col items-center justify-center text-center text-muted"><LineChart size={36}/><p className="mt-3 text-sm">Choose rules and run a test. Calculations are deterministic; AI does not produce the numbers.</p></div>}</section></div>}

    {tab === "Ladder" && <section className="rounded-2xl border border-line bg-surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-muted">Strategy campaign</p><h2 className="mt-1 text-xl font-bold">Reusable ladder simulator</h2></div><button onClick={simulate} disabled={!backtest} className="rounded-lg bg-accent px-4 py-2 text-xs font-bold text-white disabled:opacity-40">Simulate latest test</button></div>{ladder ? <><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-surface-subtle p-4"><p className="text-xs text-muted">Status</p><p className="mt-1 text-lg font-bold uppercase">{ladder.result.status}</p></div><div className="rounded-xl bg-surface-subtle p-4"><p className="text-xs text-muted">Current step</p><p className="mt-1 text-lg font-bold">{ladder.result.currentStep}/{ladder.result.steps.length}</p></div><div className="rounded-xl bg-surface-subtle p-4"><p className="text-xs text-muted">Final balance</p><p className="mt-1 text-lg font-bold">${ladder.result.finalBalance.toLocaleString()}</p></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5">{ladder.result.steps.map((step: AnyMap) => <div key={step.step} className={`rounded-lg border p-3 ${step.status === "passed" ? "border-emerald-500/40 bg-emerald-500/10" : step.status === "failed" ? "border-red-500/40 bg-red-500/10" : "border-line"}`}><p className="text-xs font-bold">Step {step.step}</p><p className="mt-1 text-[10px] text-muted">{step.status} · {step.attempts} attempts</p></div>)}</div></> : <p className="mt-10 text-center text-sm text-muted">Run a backtest first, then apply its trade sequence to a capped ladder campaign.</p>}</section>}

    {tab === "Journal" && <div className="grid gap-4 lg:grid-cols-[.35fr_.65fr]"><section className="rounded-2xl border border-line bg-surface p-5"><Upload size={20} className="text-accent"/><h2 className="mt-3 font-bold">Import broker history</h2><p className="mt-2 text-xs leading-5 text-muted">CSV supports common symbol, side, entry, exit, time, P&amp;L and ticket columns. Duplicate ticket IDs are skipped.</p><form onSubmit={uploadCsv} className="mt-4"><input name="file" type="file" accept=".csv,text/csv" required className="w-full text-xs text-muted"/><button className="mt-4 w-full rounded-lg bg-accent py-2.5 text-xs font-bold text-white">Upload CSV</button></form></section><section className="overflow-hidden rounded-2xl border border-line bg-surface"><div className="border-b border-line p-5"><h2 className="font-bold">Trade journal</h2><p className="mt-1 text-xs text-muted">{journal.entries?.length ?? 0} recent trades</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-surface-subtle text-muted"><tr><th className="p-3">Market</th><th className="p-3">Side</th><th className="p-3">Entry</th><th className="p-3">Result</th><th className="p-3">Strategy</th></tr></thead><tbody>{(journal.entries ?? []).slice(0,20).map((item: AnyMap) => <tr key={item.id} className="border-t border-line"><td className="p-3 font-bold">{item.instrument}</td><td className="p-3 uppercase">{item.direction}</td><td className="p-3">{item.entry_price}</td><td className={`p-3 ${Number(item.result_usd) >= 0 ? "text-emerald-500" : "text-red-500"}`}>{item.result_usd ?? "Open"}</td><td className="p-3 text-muted">{item.strategy ?? "—"}</td></tr>)}</tbody></table>{!journal.entries?.length && <p className="p-8 text-center text-sm text-muted">No trades logged yet.</p>}</div></section></div>}

    {tab === "Connectors" && <section><div className="mb-4 flex items-start gap-2"><ShieldCheck className="mt-0.5 text-emerald-500" size={18}/><div><p className="text-sm font-bold">External live-data connectors</p><p className="mt-1 text-xs text-muted">Buddies OS AI is already configured and used automatically. Market-data credentials are encrypted server-side and never returned to the browser.</p></div></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{connectors.map((item: AnyMap) => <ConnectorCard key={item.id} item={item} onDone={load}/>)}</div>{!connectors.length && <p className="rounded-xl border border-line bg-surface p-8 text-center text-sm text-muted">Connector catalogue will appear after the database migration is applied.</p>}</section>}
    {busy === "load" && <div className="fixed bottom-5 right-5 flex items-center gap-2 rounded-full bg-ink px-4 py-2 text-xs font-bold text-canvas"><Loader2 className="animate-spin" size={14}/> Loading lab</div>}
  </div></main>;
}

function ConnectorCard({ item, onDone }: { item: AnyMap; onDone: () => Promise<void> }) {
  const [secret, setSecret] = useState(""), [busy, setBusy] = useState(false), [result, setResult] = useState("");
  const act = async (action: string) => { try { setBusy(true); const data = await api("/api/trading-lab/connectors", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider: item.id, action, secret }) }); setResult(data.message || data.status || "Saved and verified"); setSecret(""); await onDone(); } catch (e) { setResult((e as Error).message); } finally { setBusy(false); } };
  const tradingView = item.id === "tradingview_webhook";
  return <article className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-start justify-between"><Cable size={19} className="text-accent"/><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${item.profile?.status === "connected" ? "bg-emerald-500/10 text-emerald-500" : "bg-surface-subtle text-muted"}`}>{item.profile?.status ?? "not connected"}</span></div><h2 className="mt-4 font-bold">{item.name}</h2><p className="mt-2 min-h-12 text-xs leading-5 text-muted">{item.note}</p>{item.auth !== "none" && <><input type="password" value={secret} onChange={e => setSecret(e.target.value)} placeholder={item.profile?.masked_secret ?? (tradingView ? "Create a dedicated 16+ character secret" : "API key")} className="mt-3 w-full rounded-lg border border-line bg-canvas p-2.5 text-xs"/>{tradingView && <p className="mt-1 text-[10px] text-muted">Use a new webhook-only secret—not your TradingView password.</p>}</>}<div className="mt-3 flex gap-2"><button onClick={() => act("test")} disabled={busy} className="flex-1 rounded-lg border border-line py-2 text-xs font-bold">Test</button><button onClick={() => act("save")} disabled={busy} className="flex-1 rounded-lg bg-accent py-2 text-xs font-bold text-white">Save</button></div>{tradingView && item.webhookUrl && <div className="mt-3 rounded-lg bg-surface-subtle p-3"><p className="text-[10px] font-bold uppercase text-muted">Webhook URL</p><button onClick={() => void navigator.clipboard.writeText(item.webhookUrl)} className="mt-1 break-all text-left text-[11px] font-semibold text-accent">{item.webhookUrl}</button><p className="mt-3 text-[10px] font-bold uppercase text-muted">Alert message template</p><button onClick={() => void navigator.clipboard.writeText('{"secret":"YOUR_DEDICATED_SECRET","alert_id":"{{time}}-{{ticker}}-{{interval}}","symbol":"{{ticker}}","timeframe":"{{interval}}","price":"{{close}}","action":"watch"}')} className="mt-1 text-left text-[10px] leading-4 text-muted">Click to copy the JSON template. Replace YOUR_DEDICATED_SECRET with the webhook-only secret you saved.</button></div>}{result && <p className="mt-2 text-[11px] text-muted">{result}</p>}</article>;
}
