import { analysisContribution, analysisEvidenceSchema } from "@/lib/trading-lab/analysis-evidence";
import { chartIndicators } from "@/lib/trading-lab/chart-indicators";
const asOf="2026-09-10T08:00:00Z";
const pillar=(stance="supports")=>({stance,evidence:stance==="unknown"?"":"Observed evidence",source:stance==="unknown"?"":"Manual source: 15m EMA20/50",asOf:stance==="unknown"?null:asOf});
const trade=(r:number,volume="supports",fundamental="supports")=>({status:"closed",net_pnl:r*10,planned_risk_amount:10,locked_at:"2026-09-10T08:01:00Z",open_snapshot:{occurredAt:"2026-09-10T08:02:00Z"},plan_snapshot:{observedAt:asOf,validUntil:"2026-09-10T09:00:00Z",analysisEvidence:{schemaVersion:1,method:"manual_pretrade",technical:pillar(),volume:pillar(volume),fundamental:pillar(fundamental)}},review_snapshot:null});
test("all seven combinations use known comparators and never add probabilities",()=>{const result=analysisContribution([trade(2),trade(-1,"opposes"),trade(1,"unknown")]);const both=result.rows.find(r=>r.keys.join("+")==="technical+volume")!;expect(both.aligned).toMatchObject({count:1,expectancyR:2,winRate:100,referenceCount:0,referenceExpectancyR:null});expect(both.other).toMatchObject({count:1,expectancyR:-1});expect(both.differenceR).toBe(3);expect(both.unknown).toBe(1);expect(result.rows).toHaveLength(7);});
test("missing historic labels stay excluded and unknown is not a failed signal",()=>{const t=trade(1);delete (t.plan_snapshot as any).analysisEvidence;const r=analysisContribution([t,trade(-1,"unknown")]);expect(r.excluded).toBe(1);const volume=r.rows.find(x=>x.keys.join()==="volume")!;expect(volume.aligned.count).toBe(0);expect(volume.other.count).toBe(0);expect(volume.differenceR).toBeNull();});
test("late evidence, pre-capture fills and expired fills cannot enter analysis cohorts",()=>{const late=trade(1);late.plan_snapshot.analysisEvidence.technical.asOf="2026-09-10T08:03:00Z";const early=trade(1);early.open_snapshot.occurredAt=asOf;const expired=trade(1);expired.open_snapshot.occurredAt=expired.plan_snapshot.validUntil;expect(analysisContribution([late,early,expired]).eligible).toBe(0);});
test("known judgments require source, time and reasoning",()=>{const a=trade(1).plan_snapshot.analysisEvidence;expect(analysisEvidenceSchema.safeParse(a).success).toBe(true);a.technical.source="";expect(analysisEvidenceSchema.safeParse(a).success).toBe(false);});
test("strategy reference remains separately evidenced rather than substituting actual P&L",()=>{const t:any=trade(-1);t.review_snapshot={strategyReference:{r:2}};const aligned=analysisContribution([t]).rows[0].aligned;expect(aligned.expectancyR).toBe(-1);expect(aligned.referenceExpectancyR).toBe(2);expect(aligned.referenceCount).toBe(1);});
const candles=(n:number,rising=false)=>Array.from({length:n},(_,i)=>({time:new Date(Date.UTC(2026,8,10,0,i)).toISOString(),open:rising?100+i:100,high:rising?101+i:101,low:rising?99+i:99,close:rising?100+i:100,volume:0}));
test("chart indicators respect warmup and neutral flat RSI",()=>{const v=chartIndicators(candles(60));expect(v.ema20).toHaveLength(41);expect(v.ema50).toHaveLength(11);expect(v.rsi).toHaveLength(46);expect(v.rsi.every(x=>x.value===50)).toBe(true);expect(v.ema20.every(x=>x.value===100)).toBe(true);});
test("indicator values do not change when later candles are appended",()=>{const before=chartIndicators(candles(55,true)),after=chartIndicators(candles(60,true));expect(after.ema20.slice(0,before.ema20.length)).toEqual(before.ema20);expect(after.rsi.slice(0,before.rsi.length)).toEqual(before.rsi);expect(before.rsi.at(-1)?.value).toBe(100);});

test("incremental comparisons hold base analysis alignment fixed",()=>{const unrelated=trade(-20,"opposes");unrelated.plan_snapshot.analysisEvidence.technical=pillar("opposes");const r=analysisContribution([trade(2),trade(-1,"neutral"),unrelated]);expect(r.incremental[0].aligned.count).toBe(1);expect(r.incremental[0].other.count).toBe(1);expect(r.incremental[0].differenceR).toBe(3);});
