import { completedBars,evaluatePaperRules,newPaperState,paperCommand,processPaperBars,runPaperReplay,paperMetrics } from "@/lib/trading-lab/paper-engine";
import { paperConfigSchema,strategyCapabilities } from "@/lib/trading-lab/paper-contracts";
import { strategyVersionSchema } from "@/lib/trading-lab/strategy-schema";
import { z } from "zod";
import { chatActionSchema } from "@/lib/trading-lab/chat";
import { paperCommandSchema } from "@/lib/trading-lab/paper-contracts";
import { parseChatReply } from "@/lib/trading-lab/chat";
const id="10000000-0000-4000-8000-000000000001", plan="10000000-0000-4000-8000-000000000002", order="10000000-0000-4000-8000-000000000003";
const start=Date.parse("2026-09-07T08:00:00Z");const at=(m:number)=>new Date(start+m*60000).toISOString();
const bar=(m:number,open=100,high=101,low=99,close=100)=>({time:at(m),open,high,low,close,volume:100});
const config=paperConfigSchema.parse({symbol:"XAU/USD",currency:"USD",quantityUnit:"units",contractSize:1,tickSize:.01,quantityStep:.1,minimumQuantity:.1,marginRate:0,initialCapital:1000,riskAmount:10,spread:0,slippage:0,commissionPerUnit:0,financingPerUnitDay:0,sessionTimezone:"UTC",sessionStart:"00:00",sessionEnd:"00:00",weekdays:[0,1,2,3,4,5,6],maxDailyLossPct:10,maxDrawdownPct:20,maxConcurrentPositions:1,maxTradesPerSession:20,targetSample:20,maxDataAgeSeconds:180,feed:"twelve_data_1min",ambiguityPolicy:"conservative_stop_first",stopPolicy:"cancel_orders_close_next_bar",contractEvidence:"Isolated test contract"});
const strategy=strategyVersionSchema.parse({schemaVersion:1,name:"Test",description:"",market:"gold",symbols:["XAU/USD"],direction:"long",timeframes:{context:[],setup:"1m",trigger:"1m"},entry:{logic:"all",conditions:[{id:"close",left:"close",operator:"gt",right:0}]},exit:{stopType:"fixed",stopValue:5,targetType:"risk_multiple",targetValue:2},sizing:{type:"fixed_risk_usd",value:10},safety:{maxDailyLossPct:10,maxDrawdownPct:20,maxConcurrentPositions:1,maxTradesPerSession:20,eventVeto:false},execution:{timing:"next_open",spread:0,commission:0,slippage:0}});
function manual(c=config){let state=newPaperState(id,"manual",c,at(0));state=paperCommand(state,c,{action:"start"},at(0));return paperCommand(state,c,{action:"order",order:{orderId:order,planId:plan,direction:"long",type:"market",entry:100,stopLoss:95,takeProfit:110,quantity:2,expiresAt:at(60),reason:"Test"}},at(0));}

describe("paper execution evidence",()=>{
  test("realizes P&L at exit only; keeps unrealized equity separate",()=>{const a=processPaperBars(manual(),config,strategy,[bar(0,100,105,99,104)],at(1));expect(a.state.balance).toBe(1000);expect(a.state.equity).toBe(1008);expect(a.effects.map(e=>e.kind)).toEqual(["open"]);const b=processPaperBars(a.state,config,strategy,[bar(1,104,111,103,110)],at(2));expect(b.state.balance).toBe(1020);expect(b.effects[0].kind).toBe("close");expect(paperMetrics(b.state).expectancyR).toBe(2);});
  test("stop gaps fill beyond the stop and include costs once",()=>{const c={...config,commissionPerUnit:1,slippage:.5,riskAmount:20};const a=processPaperBars(manual(c),c,strategy,[bar(0)],at(1));const b=processPaperBars(a.state,c,strategy,[bar(1,90,92,88,91)],at(2));const o=b.state.orders[0];expect(o.averageEntry).toBe(100.5);expect(o.exitNotional/o.exitQuantity).toBe(89.5);expect(o.gross-o.fees).toBe(-26);expect(b.state.balance).toBe(974);});
  test("ambiguous SL/TP is a recorded conservative assumption",()=>{const r=processPaperBars(manual(),config,strategy,[bar(0,100,112,94,102)],at(1));expect(r.state.balance).toBe(990);expect(r.state.orders[0].assumptions.join(" ")).toContain("actual event order unknown");});
  test("cannot fill before a submitted decision or use an unfinished bar",()=>{let s=newPaperState(id,"manual",config,at(0));s.status="running";s=paperCommand(s,config,{action:"order",order:{orderId:order,planId:plan,direction:"long",type:"market",entry:100,stopLoss:95,takeProfit:110,quantity:2,expiresAt:at(60),reason:"Test"}},at(.5));const r=processPaperBars(s,config,strategy,[bar(0),bar(1)],at(1.5));expect(r.effects).toHaveLength(0);expect(r.state.lastTime).toBe(at(0));});
  test("duplicate price delivery does not duplicate fills",()=>{const a=processPaperBars(manual(),config,strategy,[bar(0)],at(1));const b=processPaperBars(a.state,config,strategy,[bar(0)],at(1));expect(b.effects).toEqual([]);expect(b.state).toEqual(a.state);});
  test("partial entries followed by partial/final exits reconcile",()=>{const c={...config,maxFillQuantity:1};let r=processPaperBars(manual(c),c,strategy,[bar(0),bar(1)],at(2));expect(r.effects.map(e=>e.kind)).toEqual(["open","add_fill"]);let s=paperCommand(r.state,c,{action:"close",orderId:order,quantity:1,reason:"Reduce"},at(2));r=processPaperBars(s,c,strategy,[bar(2,105,106,104,105)],at(3));expect(r.effects[0].kind).toBe("partial_exit");expect(r.state.balance).toBe(1005);s=paperCommand(r.state,c,{action:"close",orderId:order,reason:"Finish"},at(3));r=processPaperBars(s,c,strategy,[bar(3,107,108,106,107)],at(4));expect(r.effects[0].payload.pnlAmount).toBe(12);expect(r.state.balance).toBe(1012);expect(r.state.orders[0].exitNotional).toBe(212);});
  test("missing feed pauses evidence until explicit acknowledgment",()=>{const a=processPaperBars(manual(),config,strategy,[bar(0)],at(1));const b=processPaperBars(a.state,config,strategy,[bar(3)],at(4));expect(b.state.status).toBe("failed");expect(b.state.lastTime).toBe(at(0));expect(b.effects).toEqual([]);const s=paperCommand(b.state,config,{action:"resume"},at(4));const c=processPaperBars(s,config,strategy,[bar(3)],at(4));expect(c.state.orders[0].assumptions.join()).toContain("Missing market evidence");});
  test("completed timeframe aggregation excludes incomplete/gapped buckets",()=>{const bars=Array.from({length:10},(_,i)=>bar(i));expect(completedBars(bars,300,start+4*60000)).toHaveLength(0);expect(completedBars(bars,300,start+5*60000)).toHaveLength(1);expect(completedBars(bars.filter((_,i)=>i!==2),300,start+10*60000)).toHaveLength(1);});
  test("unsupported/manual checks stay unknown and block replay",()=>{const s={...strategy,entry:{logic:"all",conditions:[{id:"vsa",left:"manual:VSA",operator:"eq",right:true}]}};expect(strategyCapabilities(s).some(x=>x.status==="manual")).toBe(true);expect(evaluatePaperRules(s,[bar(0)],start+60000,"long").status).toBe("unknown");expect(()=>runPaperReplay(id,config,s,Array.from({length:60},(_,i)=>bar(i)))).toThrow(/unsupported/);});
  test("automatic decision is evaluated before the next bar execution",()=>{const r=runPaperReplay(id,config,strategy,[bar(0),bar(1),bar(2,100,111,99,110)]);expect(r.orders[0].submittedAt).toBe(at(1));expect(r.orders[0].openedAt).toBe(at(1));expect(r.balance).toBe(1020);});
  test("resuming from state produces the same replay as one chronological pass",()=>{const bars=Array.from({length:20},(_,i)=>bar(i,100,101,99,100));let s=newPaperState(id,"replay",config,at(0));s.status="running";const full=processPaperBars(s,config,strategy,bars,at(20));const first=processPaperBars(s,config,strategy,bars.slice(0,8),at(8));const rest=processPaperBars(first.state,config,strategy,bars.slice(8),at(20));expect(rest.state).toEqual(full.state);});
  test("out-of-order or impossible prices are rejected",()=>{expect(()=>processPaperBars(manual(),config,strategy,[bar(1),bar(0)],at(2))).toThrow(/chronological/);expect(()=>processPaperBars(manual(),config,strategy,[bar(0,100,99,98,100)],at(1))).toThrow(/valid prices/);});
});
describe("chat proposals",()=>{
  test("action contracts produce complete JSON schemas for the shared model provider",()=>{expect(JSON.stringify(z.toJSONSchema(chatActionSchema,{unrepresentable:"any",cycles:"ref"}))).toContain("save_strategy");expect(JSON.stringify(z.toJSONSchema(paperCommandSchema))).toContain("maxDataAgeSeconds");});
  test("malformed actions never become approval candidates",()=>{const r=parseChatReply('Here is a draft. <lab_action>{"kind":"send_live_order"}</lab_action>');expect(r.action).toBeNull();expect(r.content).not.toContain("<lab_action>");});
  test("strategy revisions retain the exact owned family reference",()=>{const r=parseChatReply(`Review the revision.<lab_action>${JSON.stringify({kind:"save_strategy",input:{definition:strategy,strategyId:id,changeNote:"Required confirmation"}})}</lab_action>`);expect(r.action?.kind).toBe("save_strategy");expect((r.action?.input as any).strategyId).toBe(id);});
});
