"use client";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Circle, Flag, Loader2, Plus } from "lucide-react";
import { useParams } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
type Milestone={id:string;title:string;description:string|null;status:string;target_date:string|null;completion_criteria:string|null;position:number};
export default function MilestonesPage(){const{id}=useParams<{id:string}>(),[items,setItems]=useState<Milestone[]>([]),[loading,setLoading]=useState(true),[title,setTitle]=useState(""),[criteria,setCriteria]=useState(""),[date,setDate]=useState("");
 const load=useCallback(async()=>{setLoading(true);const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("project_milestones").select("*").eq("project_id",id).eq("user_id",user.id).order("position");setItems(data??[]);setLoading(false)},[id]);useEffect(()=>{load()},[load]);
 async function add(){if(!title.trim())return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from("project_milestones").insert({user_id:user.id,project_id:id,title:title.trim(),completion_criteria:criteria.trim()||null,target_date:date||null,position:items.length});setTitle("");setCriteria("");setDate("");load()}
 async function toggle(m:Milestone){const done=m.status==="completed";await supabase.from("project_milestones").update({status:done?"pending":"completed",completed_at:done?null:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",m.id);load()}
 return <div className="mx-auto max-w-[860px] p-4 md:p-6"><header className="mb-5"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-accent">Outcome sequence</p><h1 className="mt-1 text-xl font-semibold text-ink">Milestones</h1><p className="mt-1 text-sm text-muted">Define the path and evidence required to call each stage complete.</p></header>
 <section className="mb-5 space-y-3 rounded-2xl border border-line bg-surface p-4"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Next milestone" className="w-full rounded-xl border border-line bg-surface-subtle px-3 py-2.5 text-sm text-ink outline-none focus:border-accent"/><textarea value={criteria} onChange={e=>setCriteria(e.target.value)} placeholder="Completion criteria" rows={2} className="w-full rounded-xl border border-line bg-surface-subtle px-3 py-2.5 text-sm text-ink outline-none focus:border-accent"/><div className="flex flex-wrap gap-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-line bg-surface-subtle px-3 py-2 text-sm text-ink"/><button onClick={add} disabled={!title.trim()} className="flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-xs font-semibold text-white disabled:opacity-40"><Plus size={14}/>Add milestone</button></div></section>
 {loading?<div className="flex gap-2 p-8 text-muted"><Loader2 className="animate-spin" size={16}/>Loading…</div>:items.length===0?<div className="rounded-2xl border border-dashed border-line p-10 text-center text-sm text-muted">No milestones defined.</div>:<div className="space-y-2">{items.map((m,i)=><article key={m.id} className="rounded-2xl border border-line bg-surface p-4"><div className="flex items-start gap-3"><button onClick={()=>toggle(m)} className={m.status==="completed"?"text-positive":"text-faint hover:text-positive"}>{m.status==="completed"?<CheckCircle2/>:<Circle/>}</button><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><h2 className={`text-sm font-semibold ${m.status==="completed"?"text-muted line-through":"text-ink"}`}><span className="mr-2 text-faint">{i+1}.</span>{m.title}</h2>{m.target_date&&<span className="flex shrink-0 items-center gap-1 text-xs text-muted"><Flag size={12}/>{new Date(m.target_date+"T00:00:00").toLocaleDateString()}</span>}</div><div className="mt-3 rounded-xl bg-surface-subtle p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-faint">Evidence of completion</p><p className="mt-1 text-sm text-ink">{m.completion_criteria||"Not defined"}</p></div></div></div></article>)}</div>}</div>}
